apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obico-docker-arc-runner-cache
  namespace: arc-runner
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
